let suggestions = [
     <a href="https://drive.google.com/file/d/14HXElh-iVnXDTpVxgju1MNs51gmvju9J/view?fbclid=IwAR2_JFLwDDkywkzE4Bzi1_4kUSvVQCALZv1fp4SoAi4twdt0O-29XNPKtnI">"La historia del color"</a>,
     <a href="https://drive.google.com/file/d/1BU3u0rbrWYNsshOLA8ntxdXRpJG8QwS4/view?fbclid=IwAR3G2bj9C_hV0YI28Pti_dlUVrF5af-NrZO0glsGLZR0GDJV3vzjPLA28oI">"Captura de periodos pendulares"</a>,
     <a href="nosotros.html">"Nosotros"</a>,
     <a href="nosotros.html">"Nuestra Historia"</a>,
     <a href="Contacto.html">"Contacto"</a>,
     <a href="Documentos.html">"Documentos"</a>,
     <a href="Investigaciones.html">"General"</a>,
     <a href="Investigaciones.html">"Investigaciones"</a>,
     <a href="Videos.html">"Videos"</a>,
     <a href="Artículos.html">"Artículos"</a>,
     <a href="Infografías.html">"Infografías"</a>,
     <a href="Novedades.html">"Noticia del día"</a>,
     <a href="Novedades.html">"Novedades"</a>,
     <a href="Novedades.html">"Lo más Reciente"</a>,
     <a href="Catalogo.html">"Catálogo"</a>,
     <a href="Investigadores.html">"Investigadores"</a>,
     <a href="Investigadores.html">"General"</a>,
     <a href="Areas.html">"Áreas"</a>,
     <a href="Contacto.html">"Tlapalti"</a>,
     <a href="https://www.facebook.com/Tlapalti-105122324896769">"Facebook"</a>,
     <a href="https://twitter.com/Tlapalti1">"Twitter"</a>,
     <a href="https://www.instagram.com/tlapalti.science/">"Instagram"</a>,
     <a href="https://www.youtube.com/channel/UC8aD9nazzFBDSM3GWnOQUUA">"Youtube"</a>,
     <a href="mailto:contacto.tlapalti@gmail.com">"Correo"</a>,
     "José Antonio",
     "Francisco Anthony",
    
    
];
