let suggestions = [
    
     "La historia del color",
     "Captura de periodos pendulares",
     "Nosotros",
     "Nuestra Historia",
     "Contacto",
     "Documentos",
     "General",
     "Investigaciones",
     "Videos",
     "Artículos",
     "Infografías",
     "Noticia del día",
     "Novedades",
     "Lo más Reciente",
     "Catálogo",
     "Investigadores",
     "General",
     "Áreas",
     "Tlapalti",
     "Facebook",
     "Twitter",
     "Instagram",
     "Youtube",
     "Correo",
     "José Antonio",
     "Francisco Anthony",
    
    
];
